#!/usr/bin/env bash
set -euo pipefail

# NorthernLights Installer for Ubuntu/Debian
# Usage: curl -fsSL https://raw.githubusercontent.com/destroptor-spec/NorthernLights/main/install.sh | bash

REPO_URL="https://github.com/destroptor-spec/NorthernLights.git"
INSTALL_DIR="$HOME/NorthernLights"
BRANCH="main"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
fail()  { err "$*"; exit 1; }

# ─── Pre-flight checks ───────────────────────────────────────────────

if [ "$(id -u)" -eq 0 ]; then
  fail "Do not run this script as root. PM2 startup requires a regular user account."
fi

if [ ! -f /etc/os-release ]; then
  fail "Cannot detect OS. This installer supports Ubuntu/Debian only."
fi

. /etc/os-release
if [[ "${ID:-}" != "ubuntu" && "${ID:-}" != "debian" ]]; then
  fail "Detected OS: ${PRETTY_NAME:-unknown}. This installer supports Ubuntu/Debian only.
For other systems, see the manual setup guide: https://github.com/destroptor-spec/NorthernLights#readme"
fi

ok "Detected: ${PRETTY_NAME:-Debian/Ubuntu}"

# ─── Helper: check if command exists ──────────────────────────────────

has() { command -v "$1" &>/dev/null; }

need_sudo() {
  if has sudo; then
    echo sudo
  else
    fail "'sudo' is required but not installed. Install it first: apt install sudo"
  fi
}

SUDO=$(need_sudo)

# ─── Install system dependencies ──────────────────────────────────────

info "Checking system dependencies..."

$SUDO apt-get update -qq

# Node.js 20.x via NodeSource
if has node; then
  NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)
  if [ "$NODE_VER" -ge 18 ]; then
    ok "Node.js $(node -v) already installed"
  else
    warn "Node.js $(node -v) is too old (< 18). Installing Node.js 20.x..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | $SUDO -E bash -
    $SUDO apt-get install -y nodejs
  fi
else
  info "Installing Node.js 20.x..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | $SUDO -E bash -
  $SUDO apt-get install -y nodejs
fi
ok "Node.js $(node -v)"

# Git
if has git; then
  ok "Git already installed"
else
  info "Installing git..."
  $SUDO apt-get install -y git
fi

# FFmpeg (includes ffprobe for audio analysis)
if has ffmpeg && has ffprobe; then
  ok "FFmpeg and ffprobe already installed"
else
  info "Installing ffmpeg (includes ffprobe for audio analysis)..."
  $SUDO apt-get install -y ffmpeg
fi

# Container runtime (prefer podman, fallback to docker)
RUNTIME=""
if has podman; then
  RUNTIME="podman"
  ok "Podman already installed"
elif has docker; then
  RUNTIME="docker"
  ok "Docker already installed"
else
  info "Installing podman (preferred container runtime)..."
  $SUDO apt-get install -y podman
  RUNTIME="podman"
fi
ok "Container runtime: $RUNTIME"

# PM2
if has pm2; then
  ok "PM2 already installed"
else
  info "Installing PM2..."
  $SUDO npm install -g pm2
fi

# ─── Clone or update repo ────────────────────────────────────────────

if [ -d "$INSTALL_DIR/.git" ]; then
  info "Existing install found at $INSTALL_DIR — updating..."
  cd "$INSTALL_DIR"
  git fetch origin "$BRANCH"
  git checkout "$BRANCH"
  git pull origin "$BRANCH"
  ok "Repository updated"
else
  info "Cloning NorthernLights to $INSTALL_DIR..."
  git clone --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
  ok "Repository cloned"
fi

# ─── Configure .env ──────────────────────────────────────────────────

if [ -f .env ]; then
  ok ".env already exists — preserving existing configuration"
else
  info "Creating .env from template..."
  cp .env.example .env

  # Auto-detect LAN IP
  LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}') || LAN_IP="localhost"
  if [ -z "$LAN_IP" ]; then
    LAN_IP="localhost"
  fi
  sed -i "s|ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=http://localhost:3001,http://${LAN_IP}:3001|" .env

  # Generate random JWT secret
  if has openssl; then
    JWT_SECRET=$(openssl rand -hex 32)
    echo "" >> .env
    echo "# Auto-generated by installer" >> .env
    echo "JWT_SECRET=${JWT_SECRET}" >> .env
  fi

  ok ".env created (LAN IP: $LAN_IP)"
fi

# ─── Build ────────────────────────────────────────────────────────────

info "Installing dependencies..."
npm install
ok "Dependencies installed"

info "Building application..."
npm run build
ok "Build complete"

# ─── PM2 setup ────────────────────────────────────────────────────────

# Stop existing instance if running
if pm2 describe northernlights &>/dev/null; then
  info "Stopping existing PM2 process..."
  pm2 stop northernlights || true
  pm2 delete northernlights || true
fi

info "Starting server with PM2..."
pm2 start "npx tsx server/index.ts" --name northernlights
pm2 save

ok "Server started"

# ─── PM2 startup (requires user to run a sudo command) ───────────────

info "Setting up PM2 startup script..."
STARTUP_CMD=$(pm2 startup 2>&1 | grep "sudo env" || true)

if [ -n "$STARTUP_CMD" ]; then
  echo ""
  echo -e "${YELLOW}To enable auto-start on boot, run this command:${NC}"
  echo ""
  echo -e "  ${CYAN}${STARTUP_CMD}${NC}"
  echo ""
  echo -e "Then run: ${CYAN}pm2 save${NC}"
else
  warn "Could not generate PM2 startup command. You may need to run 'pm2 startup' manually."
fi

# ─── Done ─────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        NorthernLights (V16) installed successfully!            ║${NC}"
echo -e "${GREEN}║  Features: AI playlists • 20D audio analysis • Worker threads  ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Try to get the LAN IP for the access URL
ACCESS_IP=$(hostname -I 2>/dev/null | awk '{print $1}') || ACCESS_IP="your-server-ip"
echo -e "  Access the app at: ${CYAN}http://${ACCESS_IP}:3001${NC}"
echo -e "  Container runtime: ${CYAN}${RUNTIME}${NC}"
echo -e "  Install location:  ${CYAN}${INSTALL_DIR}${NC}"
echo ""
echo -e "  ${YELLOW}First-time setup:${NC}"
echo -e "  1. Open the URL above in your browser"
echo -e "  2. Click ${CYAN}Create Database${NC} to start PostgreSQL"
echo -e "  3. Follow the Setup Wizard to create your admin account"
echo -e "  4. Map your music folders in Settings → Library"
echo -e "  5. The three-phase scanner will: walk → metadata → audio analysis"
echo ""
echo -e "  ${YELLOW}To update later:${NC}"
echo -e "  ${CYAN}cd ~/NorthernLights && git pull && npm install && npm run build && pm2 restart northernlights${NC}"
echo ""
